[metadata]
name = "Tropical Paradise"
author = "Sherman Rofeman"
origin_url = "https://github.com/skippyr/tropical-paradise"
[colors]
background = "#1c1307"
foreground = "#c0af8d"
cursor_bg = "#c0af8d"
cursor_fg = "#1c1307"
selection_bg = "#c0af8d"
selection_fg = "#1c1307"
ansi = [
    "#1c1307",
    "#a61300",
    "#99421d",
    "#c79038",
    "#965541",
    "#998240",
    "#ac764a",
    "#c0af8d"
]
brights = [
    "#965541",
    "#a61300",
    "#99421d",
    "#c79038",
    "#965541",
    "#998240",
    "#ac764a",
    "#c0af8d"
]
